apiVersion: v2
name: nextcloud
# renovate: datasource=helm depName=nextcloud repository=https://nextcloud.github.io/helm/
version: 6.6.10
# renovate: datasource=github-releases depName=nextcloud/server
appVersion: v32.0.0
description: A file sharing server that puts the control and security of your own data back into your hands.
keywords:
  - nextcloud
  - storage
  - http
  - web
  - php
home: https://nextcloud.com/
icon: https://cdn.rawgit.com/docker-library/docs/defa5ffc7123177acd60ddef6e16bddf694cc35f/nextcloud/logo.svg
sources:
  - https://github.com/nextcloud/helm
  - https://github.com/nextcloud/docker
maintainers:
  - name: skjnldsv
    email: skjnldsv@protonmail.com
  - name: chrisingenhaag
    email: christian.ingenhaag@googlemail.com
  - name: billimek
    email: jeff@billimek.com
dependencies:
  - name: nextcloud
    repository: https://nextcloud.github.io/helm/
    version: 8.0.2
  - name: postgresql
    version: 16.7.27
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: nextcloudContext.postgresql.enabled
    alias: nextcloud-db-pg
  - name: mariadb
    version: 22.0.0
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: nextcloudContext.mariadb.enabled
    alias: nextcloud-db
  - name: redis
    version: 22.0.7
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: nextcloudContext.redis.enabled
    alias: nextcloud-cache
